### PR TITLE
Add automated Windows builds with AppVeyor

### PR DESCRIPTION
**Pull request by EwoutH**
Adds an AppVeyor configruatuion that automatically compiles Brunsli with Visual Studio 2019.

It also uploads the [following artifacts](https://ci.appveyor.com/project/EwoutH/brunsli/build/artifacts) to AppVeyor:

- brunslicommon-static.lib
- brunslidec-c.dll
- brunslidec-static.lib
- brunslienc-c.dll
- brunslienc-static.lib
- cbrunsli.exe
- dbrunsli.exe

I could also add a Deploy aspect to the configuration, that automatically pushes these artifacts to [GitHub Releases](https://github.com/google/brunsli/releases) when a release is tagged.

### CODE REVIEW

**Comment by EwoutH** [comment]
@eustas Could you review and merge?

**Comment by eustas** [comment]
Hi. I could land this PR, but likely it won't work. Due to bureaucracy, I can not create Appveyor project right away...

**Comment by EwoutH** [comment]
Thanks for your quick response! How long do you think that it takes?

I see the [google/benchmark](https://github.com/google/benchmark) repository has an active AppVeyor project, maybe on of their maintainers could give a hand.

**Comment by EwoutH** [comment]
@eustas Could we merge anyway? That way forks and their working branches can use it at least.

**Comment by eustas** [comment]
At last, we've got appveyor project for brunsli =)

**Comment by eustas** [comment]
Thanks!

**Pull request merged**
